apiVersion: v1
kind: Service
metadata:
  name: done-service
  namespace: mylist
spec:
  ports:
  - name: http # the port name is necessary for telemetry in istio/kiali works correctly
    port: 8080
    protocol: TCP
    targetPort: 8280
  selector:
    app: done-service
