apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: mylist-ingress-vs
  namespace: mylist 
spec:
  hosts:
  - "*"
  gateways:
  - ingressgateway.istio-system.svc.cluster.local
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: webapp-mylist
        port:
          number: 8080

