apiVersion: v1
kind: Service
metadata:
  name: done-service
  namespace: mylist
spec:
  ports:
  - name: http #sem isso o istio nao funciona no kiali
    port: 8080
    protocol: TCP
    targetPort: 8280
  selector:
    app: done-service
