apiVersion: v1
kind: Service
metadata:
  name: todo-service
  namespace: mylist
spec:
  ports:
  - name: http #sem isso o istio nao funciona no kiali 
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: todo-service
