server:
  servlet:
    context-path: /mylist
  port: 8180
  
todo-service:
  endpoints:
    base-path: ${TODOSERVICE-ENDPOINT-BASE-PATH:http://localhost:8080/mylist/todo}
    receive-card: ${TODOSERVICE-ENDPOINT-RECEIVE-CARD:/cards/receive}
    
done-service:
  endpoints: 
    base-path: ${DONESERVICE-ENDPOINT-BASE-PATH:http://localhost:8280/mylist/done}
    receive-card: ${DONESERVICE-ENDPOINT-RECEIVE-CARD:/cards/receive}
    
card-service:
  endpoints:
    base-path: ${CARDSERVICE-ENDPOINT-BASE-PATH:http://localhost:8380/mylist/cards}
    update-card: ${CARDSERVICE-ENDPOINT-UPDATE-CARD:/}    