apiVersion: apps/v1
kind: Deployment
metadata:
  name: card-service
  namespace: mylist
spec:
  replicas: 1
  selector:
    matchLabels:
      app: card-service
  template:
    metadata:
      labels:
        app: card-service
        version: v1
    spec:
      containers:
      - image: card-service:v1
        name: card-service
        ports:
        - containerPort: 8380
        envFrom:
        - configMapRef:
            name: card-service
        resources:
          requests:
            cpu: 50m
          limits:
            cpu: 300m
